/*


JAVASRIPT / TYPESRIPT

*/

//console.log ("Code Runner rodando com sucesso")

//Calcular a porcentagem de um número

/*
function porcentagem(numero, por)
{
    return (numero/100) * por;
}
console.log(porcentagem(1000, 60));
*/

//Criar uma fução que execute a soma de dois valores

/*
function soma (valor1, valor2){
    return valor1 + valor2;
}

console.log(soma(20, 30));
*/

//Criar uma função que exiba a soma, subtração, multiplicação e divisão entre dois numeros

/*
function operacoes (valor1, valor2) {
    console.log (`A soma entre ${valor1} e ${valor2} é ${valor1 + valor2}`);
    console.log (`A subtração entre ${valor1} e ${valor2} é ${valor1 - valor2}`);
    console.log (`A multiplicação entre ${valor1} e ${valor2} é ${valor1 * valor2}`);
    console.log (`A divisão entre ${valor1} e ${valor2} é ${valor1 / valor2}`);
}
operacoes (50, 100);
*/

//Criar uma função que verifica se um numero inteiro é divisivel por tres e retorna como true ou false

//(true = verdadeiro)
//(false = falso)

/*
function divisivel(numeroint){
    //condicional em

    if (numeroint % 3 == 0){
        return true
        } else {
        return false
        }
        divisivel(numeroint)
}
console.log(divisivel(9))

*/

//Criar um mecanismo que exiba se um usuario está logado ou não

/*
autenticado = true;

switch (autenticado) {
    case true:
        console.log ("O usuario está logado");
        break;
        case false:
        console.log ("O usuario não está logado");
}

*/

//Fazer uma convesão de temperatura de Celsius para Fahrenheit

/*
function cpf(n) {
    return n * 1.8 + 32;
    }

console.log(cpf(20))
*/

//Fazer uma convesão de temperatura de Celsius para Fahrenheit

function fpc(n) {
return (n - 32) / 1.8;
    }

console.log(fpc(68))

